apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortune-configmap-volume
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configmap-vol-example
    spec:
     containers:
     - image: nginx:alpine
       name: web-server
       ports:
       - containerPort: 80
       volumeMounts:
       - name: config
         mountPath: /etc/nginx/conf.d
         readOnly: true
     volumes:
     - name: config
       configMap:
         name: fortune-config
