apiVersion: v1
kind: Pod
metadata:
  name: private-pod
spec:
  imagePullSecrets:                 1
  - name: mydockerhubsecret         1
  containers:
  - image: korzan1907/private:tag
    name: main
